include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = touchspoofprefs

touchspoofprefs_FILES = TSPRootListController.m
touchspoofprefs_FRAMEWORKS = UIKit
touchspoofprefs_PRIVATE_FRAMEWORKS = Preferences
touchspoofprefs_INSTALL_PATH = /Library/PreferenceBundles
touchspoofprefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
